#!/usr/bin/env python3
"""Regenerate TypeScript ABI modules for api/ and web/ from contracts/out."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
s = "// Generated by scripts/gen-abis.py from contracts/out. Do not edit by hand.\n"
for name in ["LaunchFactory", "LaunchHook", "LaunchRouter", "LaunchToken"]:
    abi = json.loads((root / f"contracts/out/{name}.sol/{name}.json").read_text())["abi"]
    s += f"export const {name[0].lower() + name[1:]}Abi = {json.dumps(abi)} as const;\n\n"
for target in ["api/src/abis.ts", "web/src/lib/abis.ts"]:
    (root / target).write_text(s)
